<?php

/**
 * cafe store api
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * this is a sample.
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\AddOrder201Response;

/**
 * AddOrder201ResponseTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\AddOrder201Response
 */
class AddOrder201ResponseTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AddOrder201Response"
     */
    public function testAddOrder201Response()
    {
        $testAddOrder201Response = new AddOrder201Response();
        $namespacedClassname = AddOrder201Response::getModelsNamespace() . '\\AddOrder201Response';
        $this->assertSame('\\' . AddOrder201Response::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "AddOrder201Response" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->markTestIncomplete(
            'Test of "id" property in "AddOrder201Response" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "menuId"
     */
    public function testPropertyMenuId()
    {
        $this->markTestIncomplete(
            'Test of "menuId" property in "AddOrder201Response" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
        $this->markTestIncomplete(
            'Test of "quantity" property in "AddOrder201Response" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "shipDate"
     */
    public function testPropertyShipDate()
    {
        $this->markTestIncomplete(
            'Test of "shipDate" property in "AddOrder201Response" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = AddOrder201Response::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
