<?php

/**
 * cafe store api
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * this is a sample.
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\MenuApi;

/**
 * MenuApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\MenuApi
 */
class MenuApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addMenu
     *
     * add menu.
     *
     * @covers ::addMenu
     */
    public function testAddMenu()
    {
        $this->markTestIncomplete(
            'Test of "addMenu" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteMenu
     *
     * delete menu.
     *
     * @covers ::deleteMenu
     */
    public function testDeleteMenu()
    {
        $this->markTestIncomplete(
            'Test of "deleteMenu" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getMenu
     *
     * list menu.
     *
     * @covers ::getMenu
     */
    public function testGetMenu()
    {
        $this->markTestIncomplete(
            'Test of "getMenu" method has not been implemented yet.'
        );
    }

    /**
     * Test case for showMenu
     *
     * show menu.
     *
     * @covers ::showMenu
     */
    public function testShowMenu()
    {
        $this->markTestIncomplete(
            'Test of "showMenu" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateMenu
     *
     * update menu.
     *
     * @covers ::updateMenu
     */
    public function testUpdateMenu()
    {
        $this->markTestIncomplete(
            'Test of "updateMenu" method has not been implemented yet.'
        );
    }
}
