<?php

/**
 * cafe store api
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * this is a sample.
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\OrderApi;

/**
 * OrderApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\OrderApi
 */
class OrderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addOrder
     *
     * add order.
     *
     * @covers ::addOrder
     */
    public function testAddOrder()
    {
        $this->markTestIncomplete(
            'Test of "addOrder" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteOrder
     *
     * .
     *
     * @covers ::deleteOrder
     */
    public function testDeleteOrder()
    {
        $this->markTestIncomplete(
            'Test of "deleteOrder" method has not been implemented yet.'
        );
    }

    /**
     * Test case for listOrder
     *
     * list order.
     *
     * @covers ::listOrder
     */
    public function testListOrder()
    {
        $this->markTestIncomplete(
            'Test of "listOrder" method has not been implemented yet.'
        );
    }

    /**
     * Test case for showOrder
     *
     * show order.
     *
     * @covers ::showOrder
     */
    public function testShowOrder()
    {
        $this->markTestIncomplete(
            'Test of "showOrder" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateOrder
     *
     * .
     *
     * @covers ::updateOrder
     */
    public function testUpdateOrder()
    {
        $this->markTestIncomplete(
            'Test of "updateOrder" method has not been implemented yet.'
        );
    }
}
