version: '3.7'

volumes:
  logs:
    driver: local
 
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
  api:
    image: php:8.1-alpine
    ports:
      - "8080:8080"
    working_dir: /var/www
    restart: always
    environment:
      docker: "true"
    volumes:
      - .:/var/www
      - logs:/var/www/logs
    command: php -S 0.0.0.0:8080 -t public  
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: cafe 
      MYSQL_USER: db_user
      MYSQK_PASSWORD: password
